# Generated by Django 4.2.7 on 2023-11-18 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherData',
            fields=[
                ('datetime', models.DateField()),
                ('tempmax', models.FloatField()),
                ('tempmin', models.FloatField()),
                ('temp', models.FloatField()),
                ('precip', models.FloatField()),
                ('precipprob', models.FloatField()),
                ('precipcover', models.FloatField()),
                ('windspeed', models.FloatField()),
                ('winddir', models.FloatField()),
                ('windgust', models.FloatField()),
                ('solarradiation', models.FloatField()),
                ('solarenergy', models.FloatField()),
                ('uvindex', models.FloatField()),
                ('unique_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
